apiVersion: 1
contactPoints:
  - orgId: 1
    name: Webhook local do laboratório
    receivers:
      - uid: devops-webhook-local
        type: webhook
        settings:
          url: http://alertas-local:8080/
          httpMethod: POST
        disableResolveMessage: false
policies:
  - orgId: 1
    receiver: Webhook local do laboratório
    group_by: [grafana_folder, alertname]
    group_wait: 0s
    group_interval: 10s
    repeat_interval: 4h
groups:
  - orgId: 1
    name: CPU - avaliação a cada 10 segundos
    folder: DevOps
    interval: 10s
    rules:
      - uid: devops-cpu-alta
        title: CPU acima de 0.5 núcleo
        condition: B
        for: 0s
        noDataState: OK
        execErrState: Alerting
        notification_settings:
          receiver: Webhook local do laboratório
          group_by: [grafana_folder, alertname]
          group_wait: 0s
          group_interval: 10s
          repeat_interval: 4h
        annotations:
          summary: Uso de CPU acima de meio núcleo no ambiente do laboratório
          description: Verifique o container estresse e o painel de CPU. Limiar didático para a carga de 60 segundos.
        labels:
          ambiente: laboratorio
          severity: warning
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: max(rate(container_cpu_usage_seconds_total{name=~"meu-container-web|estresse"}[1m]))
              instant: true
              range: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              type: math
              expression: $A > 0.5
              refId: B
